namespace CitizenPortal.Domain.Enums;

public enum ApplicationDocumentKind
{
    /// The application form PDF generated by CitizenPortal from the submitted data
    /// (Subject / Body / citizen info). There is exactly one per application.
    ApplicationForm = 0,

    /// A supporting document uploaded/attached by the citizen (e.g. ID scan, certificate).
    /// Zero or more per application. 
    Attachment = 1
}
